all: 
	curl -Lk https://github.com/BostonGlobe/globe-graphic-template/archive/master.zip > temp.zip
	unzip -q temp.zip
	mv globe-graphic-template-master/* .
	rm -rf temp.zip globe-graphic-template-master LICENSE README.md Makefile.default
	rm Makefile
	mv Makefile.basic Makefile
	@echo "\n-- HARD CODE, HARD NEWS! --\n"
